//
// Created by ellio on 6-11-2020.
//

#ifndef RAYTRACER_MESHCOLLECTIONCREATORFROMSTRING_H
#define RAYTRACER_MESHCOLLECTIONCREATORFROMSTRING_H


class MeshCollectionCreatorFromString {

};


#endif //RAYTRACER_MESHCOLLECTIONCREATORFROMSTRING_H
